# Generated by Django 4.2.6 on 2023-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_note',
            field=models.CharField(blank=True, max_length=2056),
        ),
    ]
